name: Docker Build

on: push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: hello

jobs:
    docker:
        if: github.ref == 'refs/heads/main'

        runs-on: ubuntu-latest
        steps:

        - name: Repo Checkout
          uses: actions/checkout@v3

        - name: Docker Build
          run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest -f .github/workflows/Dockerfile .

        - name: list docker images
          run: docker images

        - name: Docker Login
          run: docker login --username="${{vars.DOCKER_USERNAME}}" --password="${{secrets.DOCKER_PASSWORD}}" \
        
        - name: Docker Publish
          run: docker push $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

    deploy:
        runs-on: ubuntu-latest
        steps:

        - name: Docker Pull and run
          run: docker run bhadridevops/hello:latest 
          



     
